# 지난시간에는...

### 검증세트
원래는 훈련세트 80%, 테스트 세트 20%로 나누어 테스트 세트를 통해 하이퍼파라메타를 결정해주었다.  
하지만 이렇게 하면 테스트 세트에 오버피팅이 될 수도 있기 때문에 그것에 대한 해결방법으로  
훈련세트 80%를 60%, 20%로 나누어, 훈련세트와 "검증세트"를 추가로 만들었었다.  
학습을 시키게 될 때, 훈련+검증 세트로 훈련을 시키고, score를 내게 될 때 검증 세트도 같이 score를 내서  
테스트 세트에 오버피팅 되지 않도록 만들어준다.

### 교차 검증
훈련세트, 검증세트를 데이터 안에서 K번 섞어서(?) 모델을 훈련하고 모델을 평가함으로써 오버피팅을 막는 방법이다.  
K번 섞는다고 해서 ***K-폴드 교차검증*** 이라고 한다.  
사이킷런에서는 5폴드가 기본으로 제공된다.  
함수 이름은 `cross_validate(model, train_input, train_target)`


# 이번 시간에는...

### 머신러닝
- 지도학습(supervised learning) - feature(X) + class(Y)
  - 회귀(예측) - Y값이 연속적
  - 분류 - Y값이 이산적
  - **지도학습의 한계** : Y값을 누군가가 정해주어야하기 때문에 인력이 필요하다. = 비용이 발생한다.
- 비지도학습(self-supervised learning) - feature(X)만 있는 것
  - 클러스터링(군집화) : 유사한 것 끼리 모아준다.
- 강화학습(reinforced learning) - X값 마저 기계가 찾는다
  - 상벌제도(Reward)

### 정형 vs 비정형 데이터
정형 데이터(Structured)는 숫자로 나타나는 데이터고,  
비정형 데이터(Unstructured)는 숫자로 나타나지 않는 데이터다.(텍스트, 오디오, 이미지, 영상...)  
보통은 정형 데이터는 머신러닝으로 처리하고, 비정형 데이터는 딥러닝으로 처리한다.

## 트리 앙상블 알고리즘
지금까지 배운 머신러닝 알고리즘 중에 가장 성능이 뛰어난 알고리즘  
대표적인 트리 앙상블 알고리즘은 ***랜덤 포레스트***  
코드로는 `RandomForestClassifier` & `RandomForestRegressor`  
결정 트리를 랜덤하게 만들어서 숲을 만드는 알고리즘이다.

### 랜덤 포레스트의 훈련 방법
#### 부트스트랩 샘플
랜덤 포레스트는 ***부트스트랩 샘플*** 이라는 것을 뽑아낸다.  
**부트스트랩 샘플 :** 중복을 허용하여 원래 데이터 크기 만큼 랜덤하게 뽑아낸다.  

>예) **동그라미1, 네모2, 세모2** 이렇게 있는데  
부트스트랩 샘플을 뽑아내면  
**세모3, 동그라미2** 이렇게 뽑아낼 수 있다는 말

이렇게 하는 이유는 결정트리의 성능이 너무 좋아 오버피팅되기 때문에  
랜덤으로 값을 뽑아내서 고의적으로 성능을 끌어내리는 것이다.

이렇게 만들어진 트리를 여러개 만들어서 일반화 하면 랜덤 포레스트가 만들어진다.  
(기본적으로 100개의 트리 생성)

In [3]:
## 랜덤포레스트

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

wine = pd.read_csv('https://bit.ly/wine_csv_data')

data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [4]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1)

# 이름은 테스트 스코어지만 train만 넣어주었기 때문에 사실 검증세트다.
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

rf.fit(train_input, train_target)
# 데이터의 중요도 출력
print(rf.feature_importances_)

# oob : 부트스트랩 샘플을 뽑아낼 때 뽑아내지 않은, 트리를 만들지 않은 샘플들
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)

rf.fit(train_input, train_target)
print(rf.oob_score_)

0.9973541965122431 0.8905151032797809
[0.23167441 0.50039841 0.26792718]
0.8934000384837406


### 엑스트라트리
랜덤포레스트와 비슷한데 부트스트랩 샘플을 사용하지 않음  
무작위성을 다른 곳에서 찾은 알고리즘 이라고 생각하면 댐  
노트 분할을 무작위로 한다(추가 설명이 필요할 것 같다...)  
가장 좋은 불순도 차이를 나타내는 것을 찾아냄  

In [5]:
## 엑스트라트리

from sklearn.ensemble import ExtraTreesClassifier

et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

et.fit(train_input, train_target)
print(et.feature_importances_)

0.9974503966084433 0.8887848893166506
[0.20183568 0.52242907 0.27573525]


### 그레이디언트 부스팅
트리 앙상블 중에 가장 좋은 알고리즘  
분류할 때는 로지스틱 함수를 썼고, 

In [6]:
## 그레이디언트 부스팅

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

gb.fit(train_input, train_target)
print(gb.feature_importances_)

## 히스토그램 기반 부스팅

# 사이킷런 1.0 버전 아래에서는 다음 라인의 주석을 해제하고 실행하세요.
# from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier

hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

from sklearn.inspection import permutation_importance

hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10,
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

result = permutation_importance(hgb, test_input, test_target, n_repeats=10,
                                random_state=42, n_jobs=-1)
print(result.importances_mean)

hgb.score(test_input, test_target)

#### XGBoost

from xgboost import XGBClassifier

xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

#### LightGBM

from lightgbm import LGBMClassifier

lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8881086892152563 0.8720430147331015
0.9464595437171814 0.8780082549788999
[0.15872278 0.68010884 0.16116839]
0.9321723946453317 0.8801241948619236
[0.08876275 0.23438522 0.08027708]
[0.05969231 0.20238462 0.049     ]


ModuleNotFoundError: No module named 'xgboost'